name: Continuous Deployment

on:
  push:
    branches:
      - master 

      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup Node.Js
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.3'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /var/www/html

            if [ ! -d ".git" ]; then
              git clone https://github.com/your-repo.git .
            fi

            git pull origin main
            
            npm install
            npm run build
            pm2 restart all
