version: 2
updates:
  - package-ecosystem: "npm"         
    directory: "/"                     
    schedule:
      interval: "weekly"               
    commit-message:
      prefix: "fix"                    

  - package-ecosystem: "github-actions" 
    directory: "/.github/workflows"                     
    schedule:
      interval: "weekly"                
    commit-message:
      prefix: "fix"                     